package com.aks.hotnews.utils.helper

import com.aks.hotnews.data.model.news.News

val newsList: List<News> = listOf(
    News(
        author = "Srishty Choudhury",
        authors = listOf("Srishty Choudhury"),
        category = "",
        id = 318577490,
        image = "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2025/05/07/2692767-operation-sindoor1.jpg",
        language = "en",
        publish_date = "2025-05-07 00:15:00",
        sentiment = -0.368,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "The Indian Armed Forces on Wednesday launched ‘Operation Sindoor’, carrying out precision strikes on nine terrorist camps in Pakistan and Pakistan-occupied Jammu and Kashmir (PoJK), days after the deadly terror attack in Pahalgam that killed 26 people. India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad. Pakistan's military spokesperson and Director General of ISPR, Lt Gen Ahmed Sharif Chaudhry has confirmed Indian missile stikes claiming that 24 impacts have been reported. Addressing a press conference at 4:08 AM on Wednesday, \\\"A total of 24 impacts have been reported by India, with different weapons.\\\" The DG ISPR said that so far 8 casualties had been reported. According to the DGISPR, four strikes were carried out in Bahwalpur's Ahmedpur East, near the Subhan mosque. The Jamia Masjid Subhan Allah is a stronghold of the Jaish-e-Mohammad and its founder Maulana Masood Azhar. The JeM have been responsible for several terror strikes in India including the Pulwama attack. DG ISPR say one mosque in the complex was destroyed. The ISPR also reported a strike in Muzaffarabad near the Bilal mosque. Strikes were also confirmed in Kotli, Muridke, Kotki Lohara in Sialkot and near Shakargarh. How far is Jaish stronghold Bahwalpur from Delhi? The distance between New Delhi and Bahawalpur is approximately 556.7 km by road and by plane, the distance is 527 km.",
        title = "Operation Sindoor: How far is Jaish stronghold Bhawalpur in Pakistan from Delhi?",
        url = "https://www.dnaindia.com/india/report-how-far-is-jaish-stronghold-bhawalpur-in-pakistan-that-has-been-targeted-under-operation-sindoor-by-india-from-delhi-india-pakistan-war-maulana-masoor-azad-3150074",
        video = null
    ),
    News(
        author = "Tribune News Service",
        authors = listOf("Tribune News Service"),
        category = "politics",
        id = 318580626,
        image = "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTgyODdhNzgwLTJhZGUtMTFmMC04NDBiLTBkMWUyZGMyZWRkYi5qcGc=",
        language = "en",
        publish_date = "2025-05-07 00:41:02",
        sentiment = -0.151,
        source_country = "in",
        summary = "India launched a precision strike operation in the early hours of Wednesday, targeting terrorist infrastructure deep inside Pakistan and Pakistan-occupied Jammu &#38; Kashmir (PoK)...",
        text = "India launched a precision strike operation in the early hours of Wednesday, targeting terrorist infrastructure deep inside Pakistan and Pakistan-occupied Jammu & Kashmir (PoK) in a significant and restrained response to the deadly Pahalgam massacre.\\n\\nAccording to the Ministry of Defence, focused strikes were carried out on nine terrorist infrastructure sites targeting the roots of cross-border terror planning.\\n\\n“Importantly, no Pakistani military facilities were hit, reflecting India’s calibrated and non-escalatory approach. This operation underscores India’s resolve to hold perpetrators accountable while avoiding unnecessary provocation,” the Ministry of Defence said.\\n\\nThe military action, dubbed ‘Operation Sindoor’, comes just days after the brutal Pahalgam terrorist attack, which claimed the lives of 25 Indian citizens and one Nepali national.\\n\\nOfficial sources indicate that the operation was planned to minimize collateral damage and ensure zero civilian casualties.\\n\\nThe government reiterated its commitment to ensuring accountability for the Pahalgam attack, calling the strikes a “message of justice and resolve”.\\n\\nFurther details regarding Operation Sindoor and its operational specifics are expected during a comprehensive briefing later on Wednesday.\\n\\nThe situation is being closely monitored by both domestic and international observers, amid concerns over potential retaliation or escalation in the region.\\n\\nMeanwhile, soon after the air strikes, Pakistan violated the ceasefire in Bhimber Gali in Poonch-Rajouri area by firing artillery gun. “Indian Army is responding appropriately in a calibrated manner,” a Defence Ministry official said.\\n\\nReportedly, Pakistan's Inter-Services Public Relations (ISPR) Director General Lt Gen Ahmed Sharif Chaudhry said that they are assessing damage and vowed retaliation.",
        title = "Operation Sindoor LIVE: India avenges Pahalgam attack; strikes 9 terror targets in Pakistan, PoK",
        url = "https://www.tribuneindia.com/liveblog/india/operation-sindoor-live-india-avenges-pahalgam-attack-strikes-9-terror-targets-in-pakistan-pok",
        video = null
    ),
    News(
        author = "Srishti Mukherjee",
        authors = listOf("Srishti Mukherjee"),
        category = "politics",
        id = 318586874,
        image = "https://www.newsx.com/wp-content/uploads/2025/05/Pakistan-army-pakistan-Pakistan-PM-Shehbaz-Sharif-Trump-operation-sindoor-india-attack-pakistan-operation-sindur-bahawalpur-india-pakistan-masood-azhar-hafiz-saed-2.webp",
        language = "en",
        publish_date = "2025-05-07 00:41:01",
        sentiment = -0.052,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "In a powerful and carefully planned counter-attack, India launched 'Operation Sindoor' on Tuesday night, striking nine terror-linked sites across Pakistan and Pakistan-Occupied Kashmir (PoK). The strike was carried out by the Army, Air Force, and Navy working together — and it was personally monitored, live, by Prime Minister Narendra Modi throughout the night.\\nThis operation was India’s direct response to the April 22 terror attack in Pahalgam, where 26 innocent civilians, including women and children, were brutally killed. That massacre had deeply shaken the country and sparked nationwide outrage. Now, exactly two weeks later, the Indian government says it has delivered justice.\\nTargets Linked to JeM and LeT Taken Out\\nAccording to top-level sources, the Indian military successfully hit and destroyed the main headquarters of Jaish-e-Mohammad (JeM) in Bahawalpur and Lashkar-e-Taiba (LeT) in Muridke. These are both globally banned terror groups that India has long accused Pakistan of sheltering.\\n“This strike shows India’s intent to finish Pakistan-sponsored terror for good. Pakistan never acted against these terror factories of globally proscribed organisations like JeM and LeT,\\\" top sources said.\\nOfficials say the strikes went much further than earlier operations like the 2016 Uri-based PoK surgical strikes or the 2019 Balakot airstrikes, which mainly targeted training camps. This time, India reportedly hit core command centers, signaling a deeper and more aggressive approach.\\nOperation Sindoor: Planned in Silence, Executed with Precision\\nSources confirmed that the mission had been quietly in the works for two full weeks, right after the Pahalgam killings. The Indian forces used special precision munitions from within Indian territory to carry out the strikes. All three military branches were involved, and the operation was designed to cause maximum damage to terror infrastructure without harming civilians.\\nDespite this, Pakistan has begun circulating false claims that the Indian attack harmed innocent people. Indian sources strongly deny this, insisting it was a clean anti-terror strike.\\n“This was a strike on terror,” one source said, while calling out Pakistan for spreading misinformation about civilian casualties.\\nNine Locations Across PoK and Pakistan Hit\\nThe Indian military targeted nine terror hubs known to be active in cross-border terrorism. These include:\\nMuzaffarabad\\nA location near Sialkot\\nAll these spots, sources say, were carefully selected based on verified intelligence.\\nPakistan Was Caught Off Guard\\nAnother top source shared that Pakistan was under the impression that India was preparing for a mock drill scheduled for Wednesday. Instead, India launched its real operation a day earlier on Tuesday night, catching Pakistan completely off guard.\\n“Yet again, a Modi-led India had stumped Pakistan with surprise and stealth, leaving it stunned,” the source said.\\nModi Gave Military Full Freedom to Respond\\nInterestingly, no one saw it coming — not even those who had been with PM Modi earlier in the day. He had a packed Tuesday with official meetings and a media event in the evening, yet he was quietly preparing for what would unfold at night.\\nExactly a week ago, the Prime Minister had given full operational freedom to the chiefs of the Army, Navy, and Air Force to determine the “mode, targets, and timing” of India’s response. In one-on-one meetings held with each service chief last week, detailed plans were reportedly presented to the PM.\\nWhy the Operation Was Named ‘Sindoor’\\nThe name ‘Sindoor’, which was approved by Prime Minister Modi himself, carries deep emotional significance. As explained by sources, it refers to the sindoor (vermillion) worn by Hindu married women — a symbol of marriage and life. After the Pahalgam attack, many women were left widowed as terrorists targeted their husbands simply for being Hindu.\\n“The way terrorists had wiped off the sindoor of multiple Hindu women in Pahalgam by killing their husbands mercilessly and by targeting them for being Hindu, India has taken revenge for them and obtained justice for the Pahalgam victims – women and children,” one official said.\\nAn image symbolizing ‘Operation Sindoor’ was shared by the Indian Army on social media, making it clear that this strike was not just military in nature, but also deeply personal for the nation.\\nAlso Read: ‘Justice Is Served’: India Hits At PoK Terror Base; Indian Army Launches Operation Sindoor",
        title = "Operation Sindoor: How Did India Strike Terror Camps In Pakistan And PoK?",
        url = "https://www.newsx.com/india/operation-sindoor-how-did-india-strike-terror-camps-in-pakistan-and-pok/",
        video = null
    ),
    News(
        author = "Srishty Choudhury",
        authors = listOf("Srishty Choudhury"),
        category = "",
        id = 318577490,
        image = "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2025/05/07/2692767-operation-sindoor1.jpg",
        language = "en",
        publish_date = "2025-05-07 00:15:00",
        sentiment = -0.368,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "The Indian Armed Forces on Wednesday launched ‘Operation Sindoor’...",
        title = "Operation Sindoor: How far is Jaish stronghold Bhawalpur in Pakistan from Delhi?",
        url = "https://www.dnaindia.com/india/report-how-far-is-jaish-stronghold-bhawalpur-in-pakistan-that-has-been-targeted-under-operation-sindoor-by-india-from-delhi-india-pakistan-war-maulana-masoor-azad-3150074",
        video = null
    ),
    News(
        author = "Tribune News Service",
        authors = listOf("Tribune News Service"),
        category = "politics",
        id = 318580626,
        image = "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTgyODdhNzgwLTJhZGUtMTFmMC04NDBiLTBkMWUyZGMyZWRkYi5qcGc=",
        language = "en",
        publish_date = "2025-05-07 00:41:02",
        sentiment = -0.151,
        source_country = "in",
        summary = "India launched a precision strike operation in the early hours of Wednesday...",
        text = "India launched a precision strike operation in the early hours of Wednesday...",
        title = "Operation Sindoor LIVE: India avenges Pahalgam attack; strikes 9 terror targets in Pakistan, PoK",
        url = "https://www.tribuneindia.com/liveblog/india/operation-sindoor-live-india-avenges-pahalgam-attack-strikes-9-terror-targets-in-pakistan-pok",
        video = null
    ),
    News(
        author = "Srishti Mukherjee",
        authors = listOf("Srishti Mukherjee"),
        category = "politics",
        id = 318586874,
        image = "https://www.newsx.com/wp-content/uploads/2025/05/Pakistan-army-pakistan-Pakistan-PM-Shehbaz-Sharif-Trump-operation-sindoor-india-attack-pakistan-operation-sindur-bahawalpur-india-pakistan-masood-azhar-hafiz-saed-2.webp",
        language = "en",
        publish_date = "2025-05-07 00:41:01",
        sentiment = -0.052,
        source_country = "in",
        summary = "India launched ‘Operation Sindoor’ on Tuesday night, striking nine terror-linked sites...",
        text = "In a powerful and carefully planned counter-attack, India launched 'Operation Sindoor'...",
        title = "Operation Sindoor: How Did India Strike Terror Camps In Pakistan And PoK?",
        url = "https://www.newsx.com/india/operation-sindoor-how-did-india-strike-terror-camps-in-pakistan-and-pok/",
        video = null
    ),
    News(
        author = null,
        authors = emptyList(),
        category = "politics",
        id = 318624118,
        image = "https://img.etimg.com/thumb/msid-120952522,resizemode-4,width-1200,height-900,imgsize-50240,overlay-economictimes/articleshow.jpg",
        language = "en",
        publish_date = "2025-05-07 04:38:08",
        sentiment = -0.137,
        source_country = "in",
        summary = "Sumathi, the mother of a victim from the Pahalgam terror attack...",
        text = "Shivamogga (Karnataka), Sumathi, the mother of Manjunath Rao...",
        title = "Operation Sindoor: Pahalgam terror attack victim's mother says she had faith in PM Modi",
        url = "https://economictimes.indiatimes.com/news/india/operation-sindoor-pahalgam-terror-attack-victims-mother-says-she-had-faith-in-pm-modi/articleshow/120952454.cms",
        video = null
    ),
    News(
        author = "Cassian Baliarsingh",
        authors = listOf("Cassian Baliarsingh"),
        category = "politics",
        id = 318624510,
        image = "https://images.odishatv.in/uploadimage/library/16_9/16_9_5/recent_photo_1746592206.webp",
        language = "en",
        publish_date = "2025-05-07 04:30:10",
        sentiment = -0.009,
        source_country = "in",
        summary = "India's Operation Sindoor exposes Pakistan's air defence flaws...",
        text = "India has successfully conducted a significant operation...",
        title = "Operation Sindoor exposes Pakistan's faulty air defence backed by ‘China-made HQ-9 system’",
        url = "https://odishatv.in/news/national/operation-sindoor-exposes-pakistan-s-faulty-air-defence-backed-by-china-made-hq-9-system-262362",
        video = null
    ),
    News(
        author = "Manasi Kamble",
        authors = listOf("Manasi Kamble"),
        category = "politics",
        id = 318630790,
        image = "https://media.assettype.com/freepressjournal/2025-05-07/4aft9el8/Manasi-Hero-Image-2025-05-07T105815.279.jpg",
        language = "en",
        publish_date = "2025-05-07 05:29:30",
        sentiment = 0.819,
        source_country = "in",
        summary = "",
        text = "In a live interview, Pakistan's Minister Attaullah Tarar insisted...",
        title = "Operation Sindoor: Pak Minister Claims, 'No Terrorist Training Camps In Pakistan'; News Anchor Fact-Checks Him On Live TV (VIDEO)",
        url = "https://www.freepressjournal.in/world/operation-sindoor-pak-minister-claims-no-terrorist-training-camps-in-pakistan-news-anchor-fact-checks-him-on-live-tv-video",
        video = null
    ),
    News(
        author = "Srishty Choudhury",
        authors = listOf("Srishty Choudhury"),
        category = "",
        id = 318577490,
        image = "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2025/05/07/2692767-operation-sindoor1.jpg",
        language = "en",
        publish_date = "2025-05-07 00:15:00",
        sentiment = -0.368,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "The Indian Armed Forces on Wednesday launched ‘Operation Sindoor’, carrying out precision strikes on nine terrorist camps in Pakistan and Pakistan-occupied Jammu and Kashmir (PoJK), days after the deadly terror attack in Pahalgam that killed 26 people. India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad. Pakistan's military spokesperson and Director General of ISPR, Lt Gen Ahmed Sharif Chaudhry has confirmed Indian missile stikes claiming that 24 impacts have been reported. Addressing a press conference at 4:08 AM on Wednesday, \\\"A total of 24 impacts have been reported by India, with different weapons.\\\" The DG ISPR said that so far 8 casualties had been reported. According to the DGISPR, four strikes were carried out in Bahwalpur's Ahmedpur East, near the Subhan mosque. The Jamia Masjid Subhan Allah is a stronghold of the Jaish-e-Mohammad and its founder Maulana Masood Azhar. The JeM have been responsible for several terror strikes in India including the Pulwama attack. DG ISPR say one mosque in the complex was destroyed. The ISPR also reported a strike in Muzaffarabad near the Bilal mosque. Strikes were also confirmed in Kotli, Muridke, Kotki Lohara in Sialkot and near Shakargarh. How far is Jaish stronghold Bahwalpur from Delhi? The distance between New Delhi and Bahawalpur is approximately 556.7 km by road and by plane, the distance is 527 km.",
        title = "Operation Sindoor: How far is Jaish stronghold Bhawalpur in Pakistan from Delhi?",
        url = "https://www.dnaindia.com/india/report-how-far-is-jaish-stronghold-bhawalpur-in-pakistan-that-has-been-targeted-under-operation-sindoor-by-india-from-delhi-india-pakistan-war-maulana-masoor-azad-3150074",
        video = null
    ),
    News(
        author = "Tribune News Service",
        authors = listOf("Tribune News Service"),
        category = "politics",
        id = 318580626,
        image = "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTgyODdhNzgwLTJhZGUtMTFmMC04NDBiLTBkMWUyZGMyZWRkYi5qcGc=",
        language = "en",
        publish_date = "2025-05-07 00:41:02",
        sentiment = -0.151,
        source_country = "in",
        summary = "India launched a precision strike operation in the early hours of Wednesday, targeting terrorist infrastructure deep inside Pakistan and Pakistan-occupied Jammu &#38; Kashmir (PoK)...",
        text = "India launched a precision strike operation in the early hours of Wednesday, targeting terrorist infrastructure deep inside Pakistan and Pakistan-occupied Jammu & Kashmir (PoK) in a significant and restrained response to the deadly Pahalgam massacre.\\n\\nAccording to the Ministry of Defence, focused strikes were carried out on nine terrorist infrastructure sites targeting the roots of cross-border terror planning.\\n\\n“Importantly, no Pakistani military facilities were hit, reflecting India’s calibrated and non-escalatory approach. This operation underscores India’s resolve to hold perpetrators accountable while avoiding unnecessary provocation,” the Ministry of Defence said.\\n\\nThe military action, dubbed ‘Operation Sindoor’, comes just days after the brutal Pahalgam terrorist attack, which claimed the lives of 25 Indian citizens and one Nepali national.\\n\\nOfficial sources indicate that the operation was planned to minimize collateral damage and ensure zero civilian casualties.\\n\\nThe government reiterated its commitment to ensuring accountability for the Pahalgam attack, calling the strikes a “message of justice and resolve”.\\n\\nFurther details regarding Operation Sindoor and its operational specifics are expected during a comprehensive briefing later on Wednesday.\\n\\nThe situation is being closely monitored by both domestic and international observers, amid concerns over potential retaliation or escalation in the region.\\n\\nMeanwhile, soon after the air strikes, Pakistan violated the ceasefire in Bhimber Gali in Poonch-Rajouri area by firing artillery gun. “Indian Army is responding appropriately in a calibrated manner,” a Defence Ministry official said.\\n\\nReportedly, Pakistan's Inter-Services Public Relations (ISPR) Director General Lt Gen Ahmed Sharif Chaudhry said that they are assessing damage and vowed retaliation.",
        title = "Operation Sindoor LIVE: India avenges Pahalgam attack; strikes 9 terror targets in Pakistan, PoK",
        url = "https://www.tribuneindia.com/liveblog/india/operation-sindoor-live-india-avenges-pahalgam-attack-strikes-9-terror-targets-in-pakistan-pok",
        video = null
    ),
    News(
        author = "Srishti Mukherjee",
        authors = listOf("Srishti Mukherjee"),
        category = "politics",
        id = 318586874,
        image = "https://www.newsx.com/wp-content/uploads/2025/05/Pakistan-army-pakistan-Pakistan-PM-Shehbaz-Sharif-Trump-operation-sindoor-india-attack-pakistan-operation-sindur-bahawalpur-india-pakistan-masood-azhar-hafiz-saed-2.webp",
        language = "en",
        publish_date = "2025-05-07 00:41:01",
        sentiment = -0.052,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "In a powerful and carefully planned counter-attack, India launched 'Operation Sindoor' on Tuesday night, striking nine terror-linked sites across Pakistan and Pakistan-Occupied Kashmir (PoK). The strike was carried out by the Army, Air Force, and Navy working together — and it was personally monitored, live, by Prime Minister Narendra Modi throughout the night.\\nThis operation was India’s direct response to the April 22 terror attack in Pahalgam, where 26 innocent civilians, including women and children, were brutally killed. That massacre had deeply shaken the country and sparked nationwide outrage. Now, exactly two weeks later, the Indian government says it has delivered justice.\\nTargets Linked to JeM and LeT Taken Out\\nAccording to top-level sources, the Indian military successfully hit and destroyed the main headquarters of Jaish-e-Mohammad (JeM) in Bahawalpur and Lashkar-e-Taiba (LeT) in Muridke. These are both globally banned terror groups that India has long accused Pakistan of sheltering.\\n“This strike shows India’s intent to finish Pakistan-sponsored terror for good. Pakistan never acted against these terror factories of globally proscribed organisations like JeM and LeT,\\\" top sources said.\\nOfficials say the strikes went much further than earlier operations like the 2016 Uri-based PoK surgical strikes or the 2019 Balakot airstrikes, which mainly targeted training camps. This time, India reportedly hit core command centers, signaling a deeper and more aggressive approach.\\nOperation Sindoor: Planned in Silence, Executed with Precision\\nSources confirmed that the mission had been quietly in the works for two full weeks, right after the Pahalgam killings. The Indian forces used special precision munitions from within Indian territory to carry out the strikes. All three military branches were involved, and the operation was designed to cause maximum damage to terror infrastructure without harming civilians.\\nDespite this, Pakistan has begun circulating false claims that the Indian attack harmed innocent people. Indian sources strongly deny this, insisting it was a clean anti-terror strike.\\n“This was a strike on terror,” one source said, while calling out Pakistan for spreading misinformation about civilian casualties.\\nNine Locations Across PoK and Pakistan Hit\\nThe Indian military targeted nine terror hubs known to be active in cross-border terrorism. These include:\\nMuzaffarabad\\nA location near Sialkot\\nAll these spots, sources say, were carefully selected based on verified intelligence.\\nPakistan Was Caught Off Guard\\nAnother top source shared that Pakistan was under the impression that India was preparing for a mock drill scheduled for Wednesday. Instead, India launched its real operation a day earlier on Tuesday night, catching Pakistan completely off guard.\\n“Yet again, a Modi-led India had stumped Pakistan with surprise and stealth, leaving it stunned,” the source said.\\nModi Gave Military Full Freedom to Respond\\nInterestingly, no one saw it coming — not even those who had been with PM Modi earlier in the day. He had a packed Tuesday with official meetings and a media event in the evening, yet he was quietly preparing for what would unfold at night.\\nExactly a week ago, the Prime Minister had given full operational freedom to the chiefs of the Army, Navy, and Air Force to determine the “mode, targets, and timing” of India’s response. In one-on-one meetings held with each service chief last week, detailed plans were reportedly presented to the PM.\\nWhy the Operation Was Named ‘Sindoor’\\nThe name ‘Sindoor’, which was approved by Prime Minister Modi himself, carries deep emotional significance. As explained by sources, it refers to the sindoor (vermillion) worn by Hindu married women — a symbol of marriage and life. After the Pahalgam attack, many women were left widowed as terrorists targeted their husbands simply for being Hindu.\\n“The way terrorists had wiped off the sindoor of multiple Hindu women in Pahalgam by killing their husbands mercilessly and by targeting them for being Hindu, India has taken revenge for them and obtained justice for the Pahalgam victims – women and children,” one official said.\\nAn image symbolizing ‘Operation Sindoor’ was shared by the Indian Army on social media, making it clear that this strike was not just military in nature, but also deeply personal for the nation.\\nAlso Read: ‘Justice Is Served’: India Hits At PoK Terror Base; Indian Army Launches Operation Sindoor",
        title = "Operation Sindoor: How Did India Strike Terror Camps In Pakistan And PoK?",
        url = "https://www.newsx.com/india/operation-sindoor-how-did-india-strike-terror-camps-in-pakistan-and-pok/",
        video = null
    ),
    News(
        author = "Srishty Choudhury",
        authors = listOf("Srishty Choudhury"),
        category = "",
        id = 318577490,
        image = "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2025/05/07/2692767-operation-sindoor1.jpg",
        language = "en",
        publish_date = "2025-05-07 00:15:00",
        sentiment = -0.368,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "The Indian Armed Forces on Wednesday launched ‘Operation Sindoor’...",
        title = "Operation Sindoor: How far is Jaish stronghold Bhawalpur in Pakistan from Delhi?",
        url = "https://www.dnaindia.com/india/report-how-far-is-jaish-stronghold-bhawalpur-in-pakistan-that-has-been-targeted-under-operation-sindoor-by-india-from-delhi-india-pakistan-war-maulana-masoor-azad-3150074",
        video = null
    ),
    News(
        author = "Tribune News Service",
        authors = listOf("Tribune News Service"),
        category = "politics",
        id = 318580626,
        image = "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTgyODdhNzgwLTJhZGUtMTFmMC04NDBiLTBkMWUyZGMyZWRkYi5qcGc=",
        language = "en",
        publish_date = "2025-05-07 00:41:02",
        sentiment = -0.151,
        source_country = "in",
        summary = "India launched a precision strike operation in the early hours of Wednesday...",
        text = "India launched a precision strike operation in the early hours of Wednesday...",
        title = "Operation Sindoor LIVE: India avenges Pahalgam attack; strikes 9 terror targets in Pakistan, PoK",
        url = "https://www.tribuneindia.com/liveblog/india/operation-sindoor-live-india-avenges-pahalgam-attack-strikes-9-terror-targets-in-pakistan-pok",
        video = null
    ),
    News(
        author = "Srishti Mukherjee",
        authors = listOf("Srishti Mukherjee"),
        category = "politics",
        id = 318586874,
        image = "https://www.newsx.com/wp-content/uploads/2025/05/Pakistan-army-pakistan-Pakistan-PM-Shehbaz-Sharif-Trump-operation-sindoor-india-attack-pakistan-operation-sindur-bahawalpur-india-pakistan-masood-azhar-hafiz-saed-2.webp",
        language = "en",
        publish_date = "2025-05-07 00:41:01",
        sentiment = -0.052,
        source_country = "in",
        summary = "India launched ‘Operation Sindoor’ on Tuesday night, striking nine terror-linked sites...",
        text = "In a powerful and carefully planned counter-attack, India launched 'Operation Sindoor'...",
        title = "Operation Sindoor: How Did India Strike Terror Camps In Pakistan And PoK?",
        url = "https://www.newsx.com/india/operation-sindoor-how-did-india-strike-terror-camps-in-pakistan-and-pok/",
        video = null
    ),
    News(
        author = null,
        authors = emptyList(),
        category = "politics",
        id = 318624118,
        image = "https://img.etimg.com/thumb/msid-120952522,resizemode-4,width-1200,height-900,imgsize-50240,overlay-economictimes/articleshow.jpg",
        language = "en",
        publish_date = "2025-05-07 04:38:08",
        sentiment = -0.137,
        source_country = "in",
        summary = "Sumathi, the mother of a victim from the Pahalgam terror attack...",
        text = "Shivamogga (Karnataka), Sumathi, the mother of Manjunath Rao...",
        title = "Operation Sindoor: Pahalgam terror attack victim's mother says she had faith in PM Modi",
        url = "https://economictimes.indiatimes.com/news/india/operation-sindoor-pahalgam-terror-attack-victims-mother-says-she-had-faith-in-pm-modi/articleshow/120952454.cms",
        video = null
    ),
    News(
        author = "Cassian Baliarsingh",
        authors = listOf("Cassian Baliarsingh"),
        category = "politics",
        id = 318624510,
        image = "https://images.odishatv.in/uploadimage/library/16_9/16_9_5/recent_photo_1746592206.webp",
        language = "en",
        publish_date = "2025-05-07 04:30:10",
        sentiment = -0.009,
        source_country = "in",
        summary = "India's Operation Sindoor exposes Pakistan's air defence flaws...",
        text = "India has successfully conducted a significant operation...",
        title = "Operation Sindoor exposes Pakistan's faulty air defence backed by ‘China-made HQ-9 system’",
        url = "https://odishatv.in/news/national/operation-sindoor-exposes-pakistan-s-faulty-air-defence-backed-by-china-made-hq-9-system-262362",
        video = null
    ),
    News(
        author = "Manasi Kamble",
        authors = listOf("Manasi Kamble"),
        category = "politics",
        id = 318630790,
        image = "https://media.assettype.com/freepressjournal/2025-05-07/4aft9el8/Manasi-Hero-Image-2025-05-07T105815.279.jpg",
        language = "en",
        publish_date = "2025-05-07 05:29:30",
        sentiment = 0.819,
        source_country = "in",
        summary = "",
        text = "In a live interview, Pakistan's Minister Attaullah Tarar insisted...",
        title = "Operation Sindoor: Pak Minister Claims, 'No Terrorist Training Camps In Pakistan'; News Anchor Fact-Checks Him On Live TV (VIDEO)",
        url = "https://www.freepressjournal.in/world/operation-sindoor-pak-minister-claims-no-terrorist-training-camps-in-pakistan-news-anchor-fact-checks-him-on-live-tv-video",
        video = null
    ),
    News(
        author = "Srishty Choudhury",
        authors = listOf("Srishty Choudhury"),
        category = "",
        id = 318577490,
        image = "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2025/05/07/2692767-operation-sindoor1.jpg",
        language = "en",
        publish_date = "2025-05-07 00:15:00",
        sentiment = -0.368,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "The Indian Armed Forces on Wednesday launched ‘Operation Sindoor’, carrying out precision strikes on nine terrorist camps in Pakistan and Pakistan-occupied Jammu and Kashmir (PoJK), days after the deadly terror attack in Pahalgam that killed 26 people. India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad. Pakistan's military spokesperson and Director General of ISPR, Lt Gen Ahmed Sharif Chaudhry has confirmed Indian missile stikes claiming that 24 impacts have been reported. Addressing a press conference at 4:08 AM on Wednesday, \\\"A total of 24 impacts have been reported by India, with different weapons.\\\" The DG ISPR said that so far 8 casualties had been reported. According to the DGISPR, four strikes were carried out in Bahwalpur's Ahmedpur East, near the Subhan mosque. The Jamia Masjid Subhan Allah is a stronghold of the Jaish-e-Mohammad and its founder Maulana Masood Azhar. The JeM have been responsible for several terror strikes in India including the Pulwama attack. DG ISPR say one mosque in the complex was destroyed. The ISPR also reported a strike in Muzaffarabad near the Bilal mosque. Strikes were also confirmed in Kotli, Muridke, Kotki Lohara in Sialkot and near Shakargarh. How far is Jaish stronghold Bahwalpur from Delhi? The distance between New Delhi and Bahawalpur is approximately 556.7 km by road and by plane, the distance is 527 km.",
        title = "Operation Sindoor: How far is Jaish stronghold Bhawalpur in Pakistan from Delhi?",
        url = "https://www.dnaindia.com/india/report-how-far-is-jaish-stronghold-bhawalpur-in-pakistan-that-has-been-targeted-under-operation-sindoor-by-india-from-delhi-india-pakistan-war-maulana-masoor-azad-3150074",
        video = null
    ),
    News(
        author = "Tribune News Service",
        authors = listOf("Tribune News Service"),
        category = "politics",
        id = 318580626,
        image = "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTgyODdhNzgwLTJhZGUtMTFmMC04NDBiLTBkMWUyZGMyZWRkYi5qcGc=",
        language = "en",
        publish_date = "2025-05-07 00:41:02",
        sentiment = -0.151,
        source_country = "in",
        summary = "India launched a precision strike operation in the early hours of Wednesday, targeting terrorist infrastructure deep inside Pakistan and Pakistan-occupied Jammu &#38; Kashmir (PoK)...",
        text = "India launched a precision strike operation in the early hours of Wednesday, targeting terrorist infrastructure deep inside Pakistan and Pakistan-occupied Jammu & Kashmir (PoK) in a significant and restrained response to the deadly Pahalgam massacre.\\n\\nAccording to the Ministry of Defence, focused strikes were carried out on nine terrorist infrastructure sites targeting the roots of cross-border terror planning.\\n\\n“Importantly, no Pakistani military facilities were hit, reflecting India’s calibrated and non-escalatory approach. This operation underscores India’s resolve to hold perpetrators accountable while avoiding unnecessary provocation,” the Ministry of Defence said.\\n\\nThe military action, dubbed ‘Operation Sindoor’, comes just days after the brutal Pahalgam terrorist attack, which claimed the lives of 25 Indian citizens and one Nepali national.\\n\\nOfficial sources indicate that the operation was planned to minimize collateral damage and ensure zero civilian casualties.\\n\\nThe government reiterated its commitment to ensuring accountability for the Pahalgam attack, calling the strikes a “message of justice and resolve”.\\n\\nFurther details regarding Operation Sindoor and its operational specifics are expected during a comprehensive briefing later on Wednesday.\\n\\nThe situation is being closely monitored by both domestic and international observers, amid concerns over potential retaliation or escalation in the region.\\n\\nMeanwhile, soon after the air strikes, Pakistan violated the ceasefire in Bhimber Gali in Poonch-Rajouri area by firing artillery gun. “Indian Army is responding appropriately in a calibrated manner,” a Defence Ministry official said.\\n\\nReportedly, Pakistan's Inter-Services Public Relations (ISPR) Director General Lt Gen Ahmed Sharif Chaudhry said that they are assessing damage and vowed retaliation.",
        title = "Operation Sindoor LIVE: India avenges Pahalgam attack; strikes 9 terror targets in Pakistan, PoK",
        url = "https://www.tribuneindia.com/liveblog/india/operation-sindoor-live-india-avenges-pahalgam-attack-strikes-9-terror-targets-in-pakistan-pok",
        video = null
    ),
    News(
        author = "Srishti Mukherjee",
        authors = listOf("Srishti Mukherjee"),
        category = "politics",
        id = 318586874,
        image = "https://www.newsx.com/wp-content/uploads/2025/05/Pakistan-army-pakistan-Pakistan-PM-Shehbaz-Sharif-Trump-operation-sindoor-india-attack-pakistan-operation-sindur-bahawalpur-india-pakistan-masood-azhar-hafiz-saed-2.webp",
        language = "en",
        publish_date = "2025-05-07 00:41:01",
        sentiment = -0.052,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "In a powerful and carefully planned counter-attack, India launched 'Operation Sindoor' on Tuesday night, striking nine terror-linked sites across Pakistan and Pakistan-Occupied Kashmir (PoK). The strike was carried out by the Army, Air Force, and Navy working together — and it was personally monitored, live, by Prime Minister Narendra Modi throughout the night.\\nThis operation was India’s direct response to the April 22 terror attack in Pahalgam, where 26 innocent civilians, including women and children, were brutally killed. That massacre had deeply shaken the country and sparked nationwide outrage. Now, exactly two weeks later, the Indian government says it has delivered justice.\\nTargets Linked to JeM and LeT Taken Out\\nAccording to top-level sources, the Indian military successfully hit and destroyed the main headquarters of Jaish-e-Mohammad (JeM) in Bahawalpur and Lashkar-e-Taiba (LeT) in Muridke. These are both globally banned terror groups that India has long accused Pakistan of sheltering.\\n“This strike shows India’s intent to finish Pakistan-sponsored terror for good. Pakistan never acted against these terror factories of globally proscribed organisations like JeM and LeT,\\\" top sources said.\\nOfficials say the strikes went much further than earlier operations like the 2016 Uri-based PoK surgical strikes or the 2019 Balakot airstrikes, which mainly targeted training camps. This time, India reportedly hit core command centers, signaling a deeper and more aggressive approach.\\nOperation Sindoor: Planned in Silence, Executed with Precision\\nSources confirmed that the mission had been quietly in the works for two full weeks, right after the Pahalgam killings. The Indian forces used special precision munitions from within Indian territory to carry out the strikes. All three military branches were involved, and the operation was designed to cause maximum damage to terror infrastructure without harming civilians.\\nDespite this, Pakistan has begun circulating false claims that the Indian attack harmed innocent people. Indian sources strongly deny this, insisting it was a clean anti-terror strike.\\n“This was a strike on terror,” one source said, while calling out Pakistan for spreading misinformation about civilian casualties.\\nNine Locations Across PoK and Pakistan Hit\\nThe Indian military targeted nine terror hubs known to be active in cross-border terrorism. These include:\\nMuzaffarabad\\nA location near Sialkot\\nAll these spots, sources say, were carefully selected based on verified intelligence.\\nPakistan Was Caught Off Guard\\nAnother top source shared that Pakistan was under the impression that India was preparing for a mock drill scheduled for Wednesday. Instead, India launched its real operation a day earlier on Tuesday night, catching Pakistan completely off guard.\\n“Yet again, a Modi-led India had stumped Pakistan with surprise and stealth, leaving it stunned,” the source said.\\nModi Gave Military Full Freedom to Respond\\nInterestingly, no one saw it coming — not even those who had been with PM Modi earlier in the day. He had a packed Tuesday with official meetings and a media event in the evening, yet he was quietly preparing for what would unfold at night.\\nExactly a week ago, the Prime Minister had given full operational freedom to the chiefs of the Army, Navy, and Air Force to determine the “mode, targets, and timing” of India’s response. In one-on-one meetings held with each service chief last week, detailed plans were reportedly presented to the PM.\\nWhy the Operation Was Named ‘Sindoor’\\nThe name ‘Sindoor’, which was approved by Prime Minister Modi himself, carries deep emotional significance. As explained by sources, it refers to the sindoor (vermillion) worn by Hindu married women — a symbol of marriage and life. After the Pahalgam attack, many women were left widowed as terrorists targeted their husbands simply for being Hindu.\\n“The way terrorists had wiped off the sindoor of multiple Hindu women in Pahalgam by killing their husbands mercilessly and by targeting them for being Hindu, India has taken revenge for them and obtained justice for the Pahalgam victims – women and children,” one official said.\\nAn image symbolizing ‘Operation Sindoor’ was shared by the Indian Army on social media, making it clear that this strike was not just military in nature, but also deeply personal for the nation.\\nAlso Read: ‘Justice Is Served’: India Hits At PoK Terror Base; Indian Army Launches Operation Sindoor",
        title = "Operation Sindoor: How Did India Strike Terror Camps In Pakistan And PoK?",
        url = "https://www.newsx.com/india/operation-sindoor-how-did-india-strike-terror-camps-in-pakistan-and-pok/",
        video = null
    ),
    News(
        author = "Srishty Choudhury",
        authors = listOf("Srishty Choudhury"),
        category = "",
        id = 318577490,
        image = "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2025/05/07/2692767-operation-sindoor1.jpg",
        language = "en",
        publish_date = "2025-05-07 00:15:00",
        sentiment = -0.368,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "The Indian Armed Forces on Wednesday launched ‘Operation Sindoor’...",
        title = "Operation Sindoor: How far is Jaish stronghold Bhawalpur in Pakistan from Delhi?",
        url = "https://www.dnaindia.com/india/report-how-far-is-jaish-stronghold-bhawalpur-in-pakistan-that-has-been-targeted-under-operation-sindoor-by-india-from-delhi-india-pakistan-war-maulana-masoor-azad-3150074",
        video = null
    ),
    News(
        author = "Tribune News Service",
        authors = listOf("Tribune News Service"),
        category = "politics",
        id = 318580626,
        image = "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTgyODdhNzgwLTJhZGUtMTFmMC04NDBiLTBkMWUyZGMyZWRkYi5qcGc=",
        language = "en",
        publish_date = "2025-05-07 00:41:02",
        sentiment = -0.151,
        source_country = "in",
        summary = "India launched a precision strike operation in the early hours of Wednesday...",
        text = "India launched a precision strike operation in the early hours of Wednesday...",
        title = "Operation Sindoor LIVE: India avenges Pahalgam attack; strikes 9 terror targets in Pakistan, PoK",
        url = "https://www.tribuneindia.com/liveblog/india/operation-sindoor-live-india-avenges-pahalgam-attack-strikes-9-terror-targets-in-pakistan-pok",
        video = null
    ),
    News(
        author = "Srishti Mukherjee",
        authors = listOf("Srishti Mukherjee"),
        category = "politics",
        id = 318586874,
        image = "https://www.newsx.com/wp-content/uploads/2025/05/Pakistan-army-pakistan-Pakistan-PM-Shehbaz-Sharif-Trump-operation-sindoor-india-attack-pakistan-operation-sindur-bahawalpur-india-pakistan-masood-azhar-hafiz-saed-2.webp",
        language = "en",
        publish_date = "2025-05-07 00:41:01",
        sentiment = -0.052,
        source_country = "in",
        summary = "India launched ‘Operation Sindoor’ on Tuesday night, striking nine terror-linked sites...",
        text = "In a powerful and carefully planned counter-attack, India launched 'Operation Sindoor'...",
        title = "Operation Sindoor: How Did India Strike Terror Camps In Pakistan And PoK?",
        url = "https://www.newsx.com/india/operation-sindoor-how-did-india-strike-terror-camps-in-pakistan-and-pok/",
        video = null
    ),
    News(
        author = null,
        authors = emptyList(),
        category = "politics",
        id = 318624118,
        image = "https://img.etimg.com/thumb/msid-120952522,resizemode-4,width-1200,height-900,imgsize-50240,overlay-economictimes/articleshow.jpg",
        language = "en",
        publish_date = "2025-05-07 04:38:08",
        sentiment = -0.137,
        source_country = "in",
        summary = "Sumathi, the mother of a victim from the Pahalgam terror attack...",
        text = "Shivamogga (Karnataka), Sumathi, the mother of Manjunath Rao...",
        title = "Operation Sindoor: Pahalgam terror attack victim's mother says she had faith in PM Modi",
        url = "https://economictimes.indiatimes.com/news/india/operation-sindoor-pahalgam-terror-attack-victims-mother-says-she-had-faith-in-pm-modi/articleshow/120952454.cms",
        video = null
    ),
    News(
        author = "Cassian Baliarsingh",
        authors = listOf("Cassian Baliarsingh"),
        category = "politics",
        id = 318624510,
        image = "https://images.odishatv.in/uploadimage/library/16_9/16_9_5/recent_photo_1746592206.webp",
        language = "en",
        publish_date = "2025-05-07 04:30:10",
        sentiment = -0.009,
        source_country = "in",
        summary = "India's Operation Sindoor exposes Pakistan's air defence flaws...",
        text = "India has successfully conducted a significant operation...",
        title = "Operation Sindoor exposes Pakistan's faulty air defence backed by ‘China-made HQ-9 system’",
        url = "https://odishatv.in/news/national/operation-sindoor-exposes-pakistan-s-faulty-air-defence-backed-by-china-made-hq-9-system-262362",
        video = null
    ),
    News(
        author = "Manasi Kamble",
        authors = listOf("Manasi Kamble"),
        category = "politics",
        id = 318630790,
        image = "https://media.assettype.com/freepressjournal/2025-05-07/4aft9el8/Manasi-Hero-Image-2025-05-07T105815.279.jpg",
        language = "en",
        publish_date = "2025-05-07 05:29:30",
        sentiment = 0.819,
        source_country = "in",
        summary = "",
        text = "In a live interview, Pakistan's Minister Attaullah Tarar insisted...",
        title = "Operation Sindoor: Pak Minister Claims, 'No Terrorist Training Camps In Pakistan'; News Anchor Fact-Checks Him On Live TV (VIDEO)",
        url = "https://www.freepressjournal.in/world/operation-sindoor-pak-minister-claims-no-terrorist-training-camps-in-pakistan-news-anchor-fact-checks-him-on-live-tv-video",
        video = null
    ),
    News(
        author = "Srishty Choudhury",
        authors = listOf("Srishty Choudhury"),
        category = "",
        id = 318577490,
        image = "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2025/05/07/2692767-operation-sindoor1.jpg",
        language = "en",
        publish_date = "2025-05-07 00:15:00",
        sentiment = -0.368,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "The Indian Armed Forces on Wednesday launched ‘Operation Sindoor’, carrying out precision strikes on nine terrorist camps in Pakistan and Pakistan-occupied Jammu and Kashmir (PoJK), days after the deadly terror attack in Pahalgam that killed 26 people. India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad. Pakistan's military spokesperson and Director General of ISPR, Lt Gen Ahmed Sharif Chaudhry has confirmed Indian missile stikes claiming that 24 impacts have been reported. Addressing a press conference at 4:08 AM on Wednesday, \\\"A total of 24 impacts have been reported by India, with different weapons.\\\" The DG ISPR said that so far 8 casualties had been reported. According to the DGISPR, four strikes were carried out in Bahwalpur's Ahmedpur East, near the Subhan mosque. The Jamia Masjid Subhan Allah is a stronghold of the Jaish-e-Mohammad and its founder Maulana Masood Azhar. The JeM have been responsible for several terror strikes in India including the Pulwama attack. DG ISPR say one mosque in the complex was destroyed. The ISPR also reported a strike in Muzaffarabad near the Bilal mosque. Strikes were also confirmed in Kotli, Muridke, Kotki Lohara in Sialkot and near Shakargarh. How far is Jaish stronghold Bahwalpur from Delhi? The distance between New Delhi and Bahawalpur is approximately 556.7 km by road and by plane, the distance is 527 km.",
        title = "Operation Sindoor: How far is Jaish stronghold Bhawalpur in Pakistan from Delhi?",
        url = "https://www.dnaindia.com/india/report-how-far-is-jaish-stronghold-bhawalpur-in-pakistan-that-has-been-targeted-under-operation-sindoor-by-india-from-delhi-india-pakistan-war-maulana-masoor-azad-3150074",
        video = null
    ),
    News(
        author = "Tribune News Service",
        authors = listOf("Tribune News Service"),
        category = "politics",
        id = 318580626,
        image = "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTgyODdhNzgwLTJhZGUtMTFmMC04NDBiLTBkMWUyZGMyZWRkYi5qcGc=",
        language = "en",
        publish_date = "2025-05-07 00:41:02",
        sentiment = -0.151,
        source_country = "in",
        summary = "India launched a precision strike operation in the early hours of Wednesday, targeting terrorist infrastructure deep inside Pakistan and Pakistan-occupied Jammu &#38; Kashmir (PoK)...",
        text = "India launched a precision strike operation in the early hours of Wednesday, targeting terrorist infrastructure deep inside Pakistan and Pakistan-occupied Jammu & Kashmir (PoK) in a significant and restrained response to the deadly Pahalgam massacre.\\n\\nAccording to the Ministry of Defence, focused strikes were carried out on nine terrorist infrastructure sites targeting the roots of cross-border terror planning.\\n\\n“Importantly, no Pakistani military facilities were hit, reflecting India’s calibrated and non-escalatory approach. This operation underscores India’s resolve to hold perpetrators accountable while avoiding unnecessary provocation,” the Ministry of Defence said.\\n\\nThe military action, dubbed ‘Operation Sindoor’, comes just days after the brutal Pahalgam terrorist attack, which claimed the lives of 25 Indian citizens and one Nepali national.\\n\\nOfficial sources indicate that the operation was planned to minimize collateral damage and ensure zero civilian casualties.\\n\\nThe government reiterated its commitment to ensuring accountability for the Pahalgam attack, calling the strikes a “message of justice and resolve”.\\n\\nFurther details regarding Operation Sindoor and its operational specifics are expected during a comprehensive briefing later on Wednesday.\\n\\nThe situation is being closely monitored by both domestic and international observers, amid concerns over potential retaliation or escalation in the region.\\n\\nMeanwhile, soon after the air strikes, Pakistan violated the ceasefire in Bhimber Gali in Poonch-Rajouri area by firing artillery gun. “Indian Army is responding appropriately in a calibrated manner,” a Defence Ministry official said.\\n\\nReportedly, Pakistan's Inter-Services Public Relations (ISPR) Director General Lt Gen Ahmed Sharif Chaudhry said that they are assessing damage and vowed retaliation.",
        title = "Operation Sindoor LIVE: India avenges Pahalgam attack; strikes 9 terror targets in Pakistan, PoK",
        url = "https://www.tribuneindia.com/liveblog/india/operation-sindoor-live-india-avenges-pahalgam-attack-strikes-9-terror-targets-in-pakistan-pok",
        video = null
    ),
    News(
        author = "Srishti Mukherjee",
        authors = listOf("Srishti Mukherjee"),
        category = "politics",
        id = 318586874,
        image = "https://www.newsx.com/wp-content/uploads/2025/05/Pakistan-army-pakistan-Pakistan-PM-Shehbaz-Sharif-Trump-operation-sindoor-india-attack-pakistan-operation-sindur-bahawalpur-india-pakistan-masood-azhar-hafiz-saed-2.webp",
        language = "en",
        publish_date = "2025-05-07 00:41:01",
        sentiment = -0.052,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "In a powerful and carefully planned counter-attack, India launched 'Operation Sindoor' on Tuesday night, striking nine terror-linked sites across Pakistan and Pakistan-Occupied Kashmir (PoK). The strike was carried out by the Army, Air Force, and Navy working together — and it was personally monitored, live, by Prime Minister Narendra Modi throughout the night.\\nThis operation was India’s direct response to the April 22 terror attack in Pahalgam, where 26 innocent civilians, including women and children, were brutally killed. That massacre had deeply shaken the country and sparked nationwide outrage. Now, exactly two weeks later, the Indian government says it has delivered justice.\\nTargets Linked to JeM and LeT Taken Out\\nAccording to top-level sources, the Indian military successfully hit and destroyed the main headquarters of Jaish-e-Mohammad (JeM) in Bahawalpur and Lashkar-e-Taiba (LeT) in Muridke. These are both globally banned terror groups that India has long accused Pakistan of sheltering.\\n“This strike shows India’s intent to finish Pakistan-sponsored terror for good. Pakistan never acted against these terror factories of globally proscribed organisations like JeM and LeT,\\\" top sources said.\\nOfficials say the strikes went much further than earlier operations like the 2016 Uri-based PoK surgical strikes or the 2019 Balakot airstrikes, which mainly targeted training camps. This time, India reportedly hit core command centers, signaling a deeper and more aggressive approach.\\nOperation Sindoor: Planned in Silence, Executed with Precision\\nSources confirmed that the mission had been quietly in the works for two full weeks, right after the Pahalgam killings. The Indian forces used special precision munitions from within Indian territory to carry out the strikes. All three military branches were involved, and the operation was designed to cause maximum damage to terror infrastructure without harming civilians.\\nDespite this, Pakistan has begun circulating false claims that the Indian attack harmed innocent people. Indian sources strongly deny this, insisting it was a clean anti-terror strike.\\n“This was a strike on terror,” one source said, while calling out Pakistan for spreading misinformation about civilian casualties.\\nNine Locations Across PoK and Pakistan Hit\\nThe Indian military targeted nine terror hubs known to be active in cross-border terrorism. These include:\\nMuzaffarabad\\nA location near Sialkot\\nAll these spots, sources say, were carefully selected based on verified intelligence.\\nPakistan Was Caught Off Guard\\nAnother top source shared that Pakistan was under the impression that India was preparing for a mock drill scheduled for Wednesday. Instead, India launched its real operation a day earlier on Tuesday night, catching Pakistan completely off guard.\\n“Yet again, a Modi-led India had stumped Pakistan with surprise and stealth, leaving it stunned,” the source said.\\nModi Gave Military Full Freedom to Respond\\nInterestingly, no one saw it coming — not even those who had been with PM Modi earlier in the day. He had a packed Tuesday with official meetings and a media event in the evening, yet he was quietly preparing for what would unfold at night.\\nExactly a week ago, the Prime Minister had given full operational freedom to the chiefs of the Army, Navy, and Air Force to determine the “mode, targets, and timing” of India’s response. In one-on-one meetings held with each service chief last week, detailed plans were reportedly presented to the PM.\\nWhy the Operation Was Named ‘Sindoor’\\nThe name ‘Sindoor’, which was approved by Prime Minister Modi himself, carries deep emotional significance. As explained by sources, it refers to the sindoor (vermillion) worn by Hindu married women — a symbol of marriage and life. After the Pahalgam attack, many women were left widowed as terrorists targeted their husbands simply for being Hindu.\\n“The way terrorists had wiped off the sindoor of multiple Hindu women in Pahalgam by killing their husbands mercilessly and by targeting them for being Hindu, India has taken revenge for them and obtained justice for the Pahalgam victims – women and children,” one official said.\\nAn image symbolizing ‘Operation Sindoor’ was shared by the Indian Army on social media, making it clear that this strike was not just military in nature, but also deeply personal for the nation.\\nAlso Read: ‘Justice Is Served’: India Hits At PoK Terror Base; Indian Army Launches Operation Sindoor",
        title = "Operation Sindoor: How Did India Strike Terror Camps In Pakistan And PoK?",
        url = "https://www.newsx.com/india/operation-sindoor-how-did-india-strike-terror-camps-in-pakistan-and-pok/",
        video = null
    ),
    News(
        author = "Srishty Choudhury",
        authors = listOf("Srishty Choudhury"),
        category = "",
        id = 318577490,
        image = "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2025/05/07/2692767-operation-sindoor1.jpg",
        language = "en",
        publish_date = "2025-05-07 00:15:00",
        sentiment = -0.368,
        source_country = "in",
        summary = "India targeted nine locations in Bahawalpur, Muridke, Gulpur, Bhimber, Chak Amru, Bagh, Kotli, Sialkot and Muzaffarabad.",
        text = "The Indian Armed Forces on Wednesday launched ‘Operation Sindoor’...",
        title = "Operation Sindoor: How far is Jaish stronghold Bhawalpur in Pakistan from Delhi?",
        url = "https://www.dnaindia.com/india/report-how-far-is-jaish-stronghold-bhawalpur-in-pakistan-that-has-been-targeted-under-operation-sindoor-by-india-from-delhi-india-pakistan-war-maulana-masoor-azad-3150074",
        video = null
    ),
    News(
        author = "Tribune News Service",
        authors = listOf("Tribune News Service"),
        category = "politics",
        id = 318580626,
        image = "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTgyODdhNzgwLTJhZGUtMTFmMC04NDBiLTBkMWUyZGMyZWRkYi5qcGc=",
        language = "en",
        publish_date = "2025-05-07 00:41:02",
        sentiment = -0.151,
        source_country = "in",
        summary = "India launched a precision strike operation in the early hours of Wednesday...",
        text = "India launched a precision strike operation in the early hours of Wednesday...",
        title = "Operation Sindoor LIVE: India avenges Pahalgam attack; strikes 9 terror targets in Pakistan, PoK",
        url = "https://www.tribuneindia.com/liveblog/india/operation-sindoor-live-india-avenges-pahalgam-attack-strikes-9-terror-targets-in-pakistan-pok",
        video = null
    ),
    News(
        author = "Srishti Mukherjee",
        authors = listOf("Srishti Mukherjee"),
        category = "politics",
        id = 318586874,
        image = "https://www.newsx.com/wp-content/uploads/2025/05/Pakistan-army-pakistan-Pakistan-PM-Shehbaz-Sharif-Trump-operation-sindoor-india-attack-pakistan-operation-sindur-bahawalpur-india-pakistan-masood-azhar-hafiz-saed-2.webp",
        language = "en",
        publish_date = "2025-05-07 00:41:01",
        sentiment = -0.052,
        source_country = "in",
        summary = "India launched ‘Operation Sindoor’ on Tuesday night, striking nine terror-linked sites...",
        text = "In a powerful and carefully planned counter-attack, India launched 'Operation Sindoor'...",
        title = "Operation Sindoor: How Did India Strike Terror Camps In Pakistan And PoK?",
        url = "https://www.newsx.com/india/operation-sindoor-how-did-india-strike-terror-camps-in-pakistan-and-pok/",
        video = null
    ),
    News(
        author = null,
        authors = emptyList(),
        category = "politics",
        id = 318624118,
        image = "https://img.etimg.com/thumb/msid-120952522,resizemode-4,width-1200,height-900,imgsize-50240,overlay-economictimes/articleshow.jpg",
        language = "en",
        publish_date = "2025-05-07 04:38:08",
        sentiment = -0.137,
        source_country = "in",
        summary = "Sumathi, the mother of a victim from the Pahalgam terror attack...",
        text = "Shivamogga (Karnataka), Sumathi, the mother of Manjunath Rao...",
        title = "Operation Sindoor: Pahalgam terror attack victim's mother says she had faith in PM Modi",
        url = "https://economictimes.indiatimes.com/news/india/operation-sindoor-pahalgam-terror-attack-victims-mother-says-she-had-faith-in-pm-modi/articleshow/120952454.cms",
        video = null
    ),
    News(
        author = "Cassian Baliarsingh",
        authors = listOf("Cassian Baliarsingh"),
        category = "politics",
        id = 318624510,
        image = "https://images.odishatv.in/uploadimage/library/16_9/16_9_5/recent_photo_1746592206.webp",
        language = "en",
        publish_date = "2025-05-07 04:30:10",
        sentiment = -0.009,
        source_country = "in",
        summary = "India's Operation Sindoor exposes Pakistan's air defence flaws...",
        text = "India has successfully conducted a significant operation...",
        title = "Operation Sindoor exposes Pakistan's faulty air defence backed by ‘China-made HQ-9 system’",
        url = "https://odishatv.in/news/national/operation-sindoor-exposes-pakistan-s-faulty-air-defence-backed-by-china-made-hq-9-system-262362",
        video = null
    )
)